#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: 53654702277-58bvtn50e2ht5vrp5iepa3ohl9itj81h.apps.googleusercontent.com
#            client-secret: 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
